
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.item
{ 
    public enum Quality
    {
        /// <summary>
        /// 白
        /// </summary>
        WHITE = 0,
        /// <summary>
        /// 蓝
        /// </summary>
        BLUE = 1,
        /// <summary>
        /// 紫
        /// </summary>
        PURPLE = 2,
        /// <summary>
        /// 红
        /// </summary>
        RED = 3,
    }

} 

